from enum import Enum

class GenreEnum(Enum):
    FANTASY = "fantasy"
    DRAMA = "drama"
    ROMANCE = "romance"
    SCIFI = "scifi"
    MYSTERY = "mystery"
    THRILLER = "thriller"
    HORROR = "horror"
    ADVENTURE = "adventure"
    HISTORICAL = "historical"
    BIOGRAPHY = "biography"
    NON_FICTION = "non_fiction"
    POETRY = "poetry"
    CLASSIC = "classic"
    YOUNG_ADULT = "young_adult"
    GRAPHIC_NOVEL = "graphic_novel"
    SELF_HELP = "self_help"
    SCIENCE_FICTION = "science_fiction"
    DYSTOPIAN = "dystopian"
    
class LanguageEnum(Enum):
    ENGLISH = "english"
    SPANISH = "spanish"
    FRENCH = "french"
    GERMAN = "german"
    ITALIAN = "italian"
    PORTUGUESE = "portuguese"
    RUSSIAN = "russian"
    CHINESE = "chinese"
    JAPANESE = "japanese"
    KOREAN = "korean"
    ARABIC = "arabic"
    HINDI = "hindi"